### ISSUE TITLE
Issue with gatsby and importing the bulma-collapsible

### ISSUE THREAD

**Issue by kalwalt** [dtbullock/bulma-collapsible#1]
Hi i'm trying your nice library with the [Gatsby framework](https://www.gatsbyjs.org/) that is based on React. Following your docs i had some problems while importing into the framework.
While importing the Sass lib i had to declare in this way:

 ``` javascript
@import "~@creativebulma/bulma-collapsible/src/sass/index.sass"
  ``` 
for the avascript lib instead:

``` javascript
import bulmaCollapsible from '@creativebulma/bulma-collapsible'
  ``` 

 I want to report also some typo errors in your doc about this last:

```diff
- import bulmaCollapsible from '~bulma-collpasible';
+ import bulmaCollapsible from '~bulma-collapsible';
```

Thank you for your attention,
Walter

**Comment by CreativeBulma** [comment]
Hi @kalwalt,

thanks for the notice. I'll update the documentation
