### ISSUE TITLE
Not able to do with JSON.parse

### ISSUE THREAD

**Issue by tanhs** [dtbullock/bulma-collapsible#4]
Not able to collapse if I change it to 
v-for="(section, index) in my.sections"
But when I change it to the following it works
v-for="(section, index) in my2.sections"

[example](https://codepen.io/tan-hai-shi/pen/qGodpP?editors=1111)

**Comment by CreativeBulma** [comment]
Hi,

You're loading data too late so ids are not set. Use `beforeMount` method instead to load your data. 

```javascript
var vm = new Vue({
  el: '[vue=app]',
  data: {
    welcome: 'bulmaCollapsible - vueJS Integration',
    my: {},
    my2: {"sections":[{"id": "a"}, {"id": "b"}]},
  },
  beforeMount() {
    this.my = JSON.parse('{"sections":[{"id": "a"}, {"id": "b"}]}');    
  },
  mounted() {    
      const collapsibles = bulmaCollapsible.attach();
  },
})
```

see https://vuejs.org/v2/api/#beforeMount
